from datetime import datetime
import os
from satquery.backend.orbit.elements import OrbitalElements
from satquery.backend.celestial.body import CelestialBody

class GMATScriptGenerator:
    """Generates valid GMAT .script files for propagating a spacecraft."""
    
    @staticmethod
    def _format_gmat_epoch(dt: datetime) -> str:
        # GMAT format: 'DD Mmm YYYY HH:MM:SS.mmm'
        # e.g., '01 Jan 2000 12:00:00.000'
        return dt.strftime('%d %b %Y %H:%M:%S.000')

    @staticmethod
    def _map_body_name(body_id: str) -> str:
        # Map internal body IDs to GMAT built-in bodies
        mapping = {
            "earth": "Earth",
            "moon": "Luna",
            "mars": "Mars"
        }
        return mapping.get(body_id.lower(), "Earth")

    @classmethod
    def generate_script(
        cls, 
        elements: OrbitalElements, 
        target_time: datetime, 
        body: CelestialBody,
        output_report_path: str,
        step_size: float = 60.0
    ) -> str:
        epoch_str = cls._format_gmat_epoch(elements.epoch)
        target_epoch_str = cls._format_gmat_epoch(target_time)
        body_name = cls._map_body_name(body.id)
        
        # Ensure path is formatted nicely for GMAT (forward slashes)
        report_path = output_report_path.replace("\\", "/")
        # Calculate elapsed seconds for propagation
        elapsed_sec = (target_time - elements.epoch).total_seconds()
        
        burns_str = ""
        mission_seq_str = "BeginMissionSequence;\n"
        
        if hasattr(elements, 'maneuvers') and elements.maneuvers:
            sorted_maneuvers = sorted(elements.maneuvers, key=lambda m: m.time_from_epoch_sec)
            
            for m in sorted_maneuvers:
                burns_str += f"""
%---------- Burn: {m.name}
Create ImpulsiveBurn {m.name};
GMAT {m.name}.CoordinateSystem = Local;
GMAT {m.name}.Origin = {body_name};
GMAT {m.name}.Axes = VNB;
GMAT {m.name}.Element1 = {m.dv_v};
GMAT {m.name}.Element2 = {m.dv_n};
GMAT {m.name}.Element3 = {m.dv_b};
"""
            
            current_time_sec = 0.0
            for m in sorted_maneuvers:
                if m.time_from_epoch_sec > current_time_sec:
                    mission_seq_str += f"Propagate DefaultProp(Sat) {{Sat.ElapsedSecs = {m.time_from_epoch_sec}}};\n"
                    current_time_sec = m.time_from_epoch_sec
                mission_seq_str += f"Maneuver {m.name}(Sat);\n"
            
            if elapsed_sec > current_time_sec:
                mission_seq_str += f"Propagate DefaultProp(Sat) {{Sat.ElapsedSecs = {elapsed_sec}}};\n"
        else:
            mission_seq_str += f"Propagate DefaultProp(Sat) {{Sat.ElapsedSecs = {elapsed_sec}}};\n"

        script = f"""% GMAT Script generated by SatQuery
% Celestial Body: {body_name}

%----------------------------------------
%---------- Spacecraft
%----------------------------------------
Create Spacecraft Sat;
GMAT Sat.DateFormat = UTCGregorian;
GMAT Sat.Epoch = '{epoch_str}';
GMAT Sat.CoordinateSystem = {body_name}MJ2000Eq;
GMAT Sat.DisplayStateType = Keplerian;
GMAT Sat.SMA = {elements.semi_major_axis_km};
GMAT Sat.ECC = {elements.eccentricity};
GMAT Sat.INC = {elements.inclination_deg};
GMAT Sat.RAAN = {elements.raan_deg};
GMAT Sat.AOP = {elements.arg_periapsis_deg};
GMAT Sat.TA = {elements.true_anomaly_deg};
{burns_str}
%----------------------------------------
%---------- ForceModels
%----------------------------------------
Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = {body_name};
GMAT DefaultProp_ForceModel.PointMasses = {{{body_name}}};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = None;

%----------------------------------------
%---------- Propagators
%----------------------------------------
Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = {step_size};
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = {step_size};
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------
Create ReportFile ReportFile1;
GMAT ReportFile1.SolverIterations = Current;
GMAT ReportFile1.UpperLeft = [ 0 0 ];
GMAT ReportFile1.Size = [ 0 0 ];
GMAT ReportFile1.RelativeZOrder = 0;
GMAT ReportFile1.Maximized = false;
GMAT ReportFile1.Filename = '{report_path}';
GMAT ReportFile1.Precision = 16;
GMAT ReportFile1.Add = {{Sat.UTCGregorian, Sat.{body_name}MJ2000Eq.X, Sat.{body_name}MJ2000Eq.Y, Sat.{body_name}MJ2000Eq.Z, Sat.{body_name}MJ2000Eq.VX, Sat.{body_name}MJ2000Eq.VY, Sat.{body_name}MJ2000Eq.VZ}};
GMAT ReportFile1.WriteHeaders = true;
GMAT ReportFile1.LeftJustify = On;
GMAT ReportFile1.ZeroFill = Off;
GMAT ReportFile1.FixedWidth = true;
GMAT ReportFile1.Delimiter = ' ';
GMAT ReportFile1.ColumnWidth = 23;
GMAT ReportFile1.WriteReport = true;

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
{mission_seq_str}
"""
        return script
